config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	resources :tweets do
		resources :comments
	end

	root 'welcome#index'

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord

	has_many :comments, dependent: :destroy

	validates :author, presence: true
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :authenticate_user!

	def create
		@tweet = Tweet.find(params[:tweet_id])
		@comment = @tweet.comments.create(comment_params)
		HardWorker.perform_async(@comment)
		#@comment.html_content = Maruku.new(@comment.content).to_html
		@comment.save
		redirect_to tweet_path(@tweet)
	end

	def destroy
		@tweet = Tweet.find(params[:tweet_id])
		@comment = @tweet.comments.find(params[:id])
		@comment.destroy
		redirect_to tweet_path(@tweet)
	end

	private
		def comment_params
			params.require(:comment).permit(:commenter, :content)
		end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	def index
		@tweets = Tweet.all
	end

	def show
		@tweet = Tweet.find(params[:id])
	end

	def new
		@tweet = Tweet.new
	end

	def edit
		@tweet = Tweet.find(params[:id])
	end

	def create
		@tweet = Tweet.new(tweet_params)
		HardWorker.perform_async(@tweet)
		#@tweet.html_content = Maruku.new(@tweet.content).to_html
		if @tweet.save
			redirect_to @tweet
		else
			render 'new'
		end
	end

	def update
		@tweet = Tweet.find(params[:id])
		HardWorker.perform_async(@tweet)
		#@tweet.html_content = Maruku.new(@tweet.content).to_html
		if @tweet.update(tweet_params)
			redirect_to @tweet
		else
			render 'edit'
		end
	end

	def destroy
		@tweet = Tweet.find(params[:id])
		@tweet.destroy

		redirect_to tweets_path
	end

	private
		def tweet_params
			params.require(:tweet).permit(:author, :content)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.haml
%p
  %strong Commenter:
  = comment.commenter
%p
  %strong Comment:
  = raw comment.html_content
%p
  = link_to 'Destroy Comment', [comment.tweet, comment], |
    method: :delete,                                     |
    data: { confirm: 'Are you sure?' }                   |

app/views/comments/_form.html.haml
= form_for([@tweet, @tweet.comments.build]) do |f|
  %p
    = f.label :commenter
    %br/
    = f.text_field :commenter
  %p
    = f.label :content
    %br/
    = f.text_area :content
  %p
    = f.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TwitterOnRails
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/tweets/_form.html.haml
= form_for @tweet do |f|
  - if @tweet.errors.any?
    #error_explanation
      %h2
        = pluralize(@tweet.errors.count, "error")
        prohibited
        this tweet from being saved:
      %ul
        - @tweet.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :author
    %br/
    = f.text_field :author
  %p
    = f.label :content
    %br/
    = f.text_area :content
  %p
    = f.submit

app/views/tweets/edit.html.haml
%h1 Editing tweet
= render 'form'
= link_to 'Back', tweets_path

app/views/tweets/index.html.haml
%h1 Listing Tweets
= link_to 'New tweet', new_tweet_path
%table
  %tr
    %th Author
    %th Content
  - @tweets.each do |tweet|
    %tr
      %td= tweet.author
      %td= tweet.content
      %td= link_to 'Show', tweet_path(tweet)
      %td= link_to 'Edit', edit_tweet_path(tweet)
      %td= link_to 'Destroy', tweet_path(tweet), |
          method: :delete,                      |
          data: { confirm: 'Are you sure?' }    |

app/views/tweets/new.html.haml
%h1 New Tweet
= render 'form'
= link_to 'Back', tweets_path

app/views/tweets/show.html.haml
%p
  %strong Author:
  = @tweet.author
%p
  %strong Content:
  = @tweet.content
%p
  %strong Html Content:
  = @tweet.html_content.html_safe

%h2 Comments
= render @tweet.comments
%h2 Add a comment:
= render 'comments/form'
= link_to 'Edit', edit_tweet_path(@tweet)
|
= link_to 'Back', tweets_path

app/views/welcome/index.html.haml
%h1 Hello, Rails!
= link_to 'My Twitter', controller: 'tweets'